apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
    - name: busybox
      image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      command: ["sleep", "3600"]
      volumeMounts:
        - name: busybox-vol
          mountPath: {{ .Values.mountPath }}
  volumes:
    - name: busybox-vol
      persistentVolumeClaim:
        claimName: busybox-pvc
