apiVersion: v1
kind: Pod
metadata:
  name: azure-disk-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: azure-disk-vol
      mountPath: /mnt/azure
  volumes:
  - name: azure-disk-vol
    persistentVolumeClaim:
      claimName: azure-disk-pvc